mybatis:
  type-aliases-package: demo.sc.entities
  mapper-locations:
  - classpath:mybatis/*
  configuration:
    cache-enabled: true

spring:
  application:
    name: springcloud-demo-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud3?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间